lsst/cp_pipe

python/lsst/cp/pipe/makeBrighterFatterKernel.py, python/lsst/cp/pipe/ptc.py
getAmpInfoCatalog() -> getAmplifiers()
=> DM-18610: Update for cameraGeom API change.

python/lsst/cp/pipe/defects.py, python/lsst/cp/pipe/makeBrighterFatterKernel.py, python/lsst/cp/pipe/ptc.py, tests/test_defects.py, tests/test_ptc.py
This PR removes all references to the `IsrConfig.doAddDistortionModel` field, which is no longer  used by `IsrTask`.
=> DM-23651: ap_pipe calls some deprecated things

bin.src/blessCalibration.py, pipelines/cpBias.yaml, pipelines/cpDark.yaml, pipelines/cpFlat.yaml, pipelines/cpFlatSingleChip.yaml, pipelines/cpFringe.yaml, python/lsst/cp/pipe/__init__.py, python/lsst/cp/pipe/cpCertify.py, python/lsst/cp/pipe/cpCombine.py, python/lsst/cp/pipe/cpDarkTask.py, python/lsst/cp/pipe/cpFlatNormTask.py, python/lsst/cp/pipe/cpFringeTask.py, tests/SConscript, ups/cp_pipe.table
Tickets/dm 21212
This ticket converts the existing pipe_drivers constructCalibs.py tasks to Gen3, and uses pipelines to handle multiprocessing, configuration, and task handling.
=> DM-21212: Update existing cp_pipe tasks to pipelineTasks

python/lsst/cp/pipe/__init__.py, python/lsst/cp/pipe/linearity.py, python/lsst/cp/pipe/ptc.py, tests/test_ptc.py
Move linearity calibration construction out of `ptc.py`, and make the new task gen3 compliant.
=>  DM-24703: Make linearity a subclass of lsst.ip.isr.IsrCalib

python/lsst/cp/pipe/measureCrosstalk.py
=> DM-26729: measureCrosstalk has a typo in the debug code.

bin.src/measureLinearity.py, python/lsst/cp/pipe/linearity.py, python/lsst/cp/pipe/ptc.py, tests/test_ptc.py
This adds the code to fit a spline linearizer to the data contained within the PTC curve.
=> DM-26545: Add spline linearizer

config/defectIsr.py, pipelines/findDefects.yaml, python/lsst/cp/pipe/cpFlatNormTask.py, python/lsst/cp/pipe/defects.py, python/lsst/cp/pipe/measureCrosstalk.py, python/lsst/cp/pipe/utils.py, tests/test_defects.py
Update Defect code to use the IsrCalib, and to work in gen3 as well as gen2.
=> DM-25424: Convert Defect to IsrCalib

python/lsst/cp/pipe/cpFlatNormTask.py
Use detector indices instead of detector-scale indices.
=> DM-27854: CpFlatNormalizationTask improperly indexes detectors

python/lsst/cp/pipe/measureCrosstalk.py
Fix bad metadata that wasn't fully tested.
=> DM-28184: gen3 crosstalk generation does not set DET_NAME correctly.

python/lsst/cp/pipe/cpCombine.py
Set the CalibCombineTask statistics properties by name.
=> DM-28457: In cpCombine.py, the config option "combine" should be a string, not the integer stats value

python/lsst/cp/pipe/utils.py
Add alternate weight methods from reference to irlsFit.
=> DM-27650: Allow irlsFit function in cp_pipe/utils.py to use a general iterative weight function.

python/lsst/cp/pipe/measureCrosstalk.py, tests/test_measureCrosstalk.py
Fix bbox issue behind the untrimmed unit test failures.
Although CrosstalkExtractTask had a config parameter for the trimmed
state, it wasn't using it consistently.
=> DM-26031: Fix broken measureCrosstalk test

python/lsst/cp/pipe/measureCrosstalk.py
Fix assumption that the ID and Name match for all detectors.
=> DM-29877: Avoid avoidable logic error in measureCrosstalk

pipelines/cpFlat.yaml, pipelines/cpFlatSingleChip.yaml, pipelines/cpFringe.yaml, python/lsst/cp/pipe/cpCombine.py
Use separate classes for the cpCombine step when it does and does not use the 'physical_filter' dimension.
The new CalibCombineByFilter Connections, Config, and Task now inherit
from their respective CalibCombine counterparts, but simply add the
new dimension.  This avoids the previous work around to have the
dimensions edited on construction.
Update the pipeline definitions for this as well.
=> DM-29699: CalibCombineConnections changes its quantum dimensions at construction

ups/cp_pipe.cfg
This PR fixes a build error caused by converting `pipe_base` to a pure-Python package in lsst/pipe_base#184.
=> DM-23330: Doxygen warnings in pipe_base

pipelines/DarkEnergyCamera/RunIsrForCrosstalkSources.yaml, pipelines/DarkEnergyCamera/cpFlat.yaml, pipelines/cpBias.yaml, pipelines/cpDark.yaml, pipelines/cpFlat.yaml, pipelines/cpFlatSingleChip.yaml, pipelines/cpFringe.yaml, pipelines/findDefects.yaml, pipelines/measureCrosstalk.yaml, pipelines/measurePhotonTransferCurve.yaml
This PR adds a DECam flat-building pipeline, and necessarily standardizes ISR task names so yaml imports work.
=> DM-29338: Incorporate Gen 3 crosstalk in HiTS runs

pipelines/Latiss/cpLinearitySolve.yaml, pipelines/cpLinearitySolve.yaml, python/lsst/cp/pipe/linearity.py, python/lsst/cp/pipe/makeBrighterFatterKernel.py, tests/test_ptc.py
This largely duplicates the gen3 connections in the brighter-fatter code (which also works off of the PTC dataset).
Additional handlers were added to ensure that the length of the output fields match between solvable and unsolveable amplifiers.  If the lengths do not match, an error is thrown by the FITS writing code.
=> DM-31096: Fix bitrot in gen3 linearity solver

pipelines/HyperSuprimeCam/cpBias.yaml, pipelines/HyperSuprimeCam/cpDark.yaml, pipelines/HyperSuprimeCam/cpFlat.yaml, pipelines/HyperSuprimeCam/cpFringe.yaml, pipelines/Latiss/cpBfkSolve.yaml, pipelines/Latiss/cpBias.yaml, pipelines/Latiss/cpDark.yaml, pipelines/Latiss/cpFlat.yaml, pipelines/Latiss/cpFringe.yaml, pipelines/Latiss/findDefects.yaml, pipelines/Latiss/findDefectsPostFlat.yaml, pipelines/Latiss/measurePtcWithLinearity.yaml, pipelines/LsstCamImSim/cpBfkSolve.yaml, pipelines/LsstCamImSim/cpBias.yaml, pipelines/LsstCamImSim/cpDark.yaml, pipelines/LsstCamImSim/cpFlat.yaml, pipelines/LsstCamImSim/cpPtc.yaml, pipelines/LsstComCam/cpBias.yaml, pipelines/LsstComCam/cpDark.yaml, pipelines/LsstComCam/cpFlat.yaml, pipelines/LsstComCam/cpPtc.yaml
Add per-camera pipeline definitions that inherit from the base definitions.
=> DM-29981: Migrate cp_pipe pipelines as defined in RFC-775

python/lsst/cp/pipe/defects.py, python/lsst/cp/pipe/ptc/cpExtractPtcTask.py
This also fixes the underlying issue that was causing Jenkins to fail: an empty string in the PTC_FIT_TYPE now throws an error on read.  I've fixed that (it now sets the field to PARTIAL in the covariance outputs), and will check that this passes before merging.
=> DM-31545: Fix cp_pipe/defects debug error

python/lsst/cp/pipe/cpCombine.py, python/lsst/cp/pipe/cpFlatNormTask.py
Fix capitalized function name.
=> DM-31301: Fix VignetteExposure name

doc/lsst.cp.pipe/tasks/lsst.cp.pipe.CpSkyCombineTask.rst, doc/lsst.cp.pipe/tasks/lsst.cp.pipe.CpSkyImageTask.rst, doc/lsst.cp.pipe/tasks/lsst.cp.pipe.CpSkyScaleMeasureTask.rst, doc/lsst.cp.pipe/tasks/lsst.cp.pipe.CpSkySubtractBackgroundTask.rst, pipelines/Latiss/cpSky.yaml, pipelines/cpSky.yaml, python/lsst/cp/pipe/__init__.py, python/lsst/cp/pipe/cpSkyTask.py
This ticket re-implements pipe_drivers constructCalib.py SkyTask in gen3, using four tasks to handle the map-reduce-map-reduce structure of the old code.
=> DM-22534: Implement cpSkyTask

python/lsst/cp/pipe/utils.py
This PR uses the `id` component added on lsst/afw#613.
=> DM-29955: Add ExposureInfo id getter

python/lsst/cp/pipe/cpCombine.py, python/lsst/cp/pipe/cpSkyTask.py, python/lsst/cp/pipe/linearity.py, python/lsst/cp/pipe/makeBrighterFatterKernel.py, python/lsst/cp/pipe/measureCrosstalk.py, python/lsst/cp/pipe/ptc/cpExtractPtcTask.py, python/lsst/cp/pipe/ptc/cpSolvePtcTask.py, python/lsst/cp/pipe/ptc/measurePtcGen2Task.py, python/lsst/cp/pipe/utils.py
This PR removes uses of `VisitInfo.getExposureId()`, which was deprecated in lsst/afw#614.
=> DM-13943: Deprecate VisitInfo.getExposureId()

python/lsst/cp/pipe/cpCombine.py, python/lsst/cp/pipe/cpFlatNormTask.py, python/lsst/cp/pipe/linearity.py, python/lsst/cp/pipe/makeBrighterFatterKernel.py, python/lsst/cp/pipe/ptc/astierCovPtcFit.py, python/lsst/cp/pipe/ptc/cpExtractPtcTask.py, python/lsst/cp/pipe/ptc/cpSolvePtcTask.py, python/lsst/cp/pipe/ptc/plotPtc.py, python/lsst/cp/pipe/ptc/plotPtcGen2.py, python/lsst/cp/pipe/utils.py, tests/test_utils.py
* Use python logging.
* Fix a lot of log usage issues.
* Ensure that `lsst.` is used as a logger prefix.
=> DM-31801: Clean up log usage

pipelines/cpBias.yaml, pipelines/cpDark.yaml, pipelines/cpFlat.yaml, pipelines/cpFlatSingleChip.yaml, pipelines/cpFringe.yaml, python/lsst/cp/pipe/cpCombine.py, python/lsst/cp/pipe/cpSkyTask.py
This uses the same tactic as pipe_tasks AssembleCoaddTask to remove the need to have all exposures in memory while doing the final calibration combine step.
=> DM-22521: enable partial image reads in cp_pipe combine to avoid memory issues

pipelines/measureCrosstalk.yaml, python/lsst/cp/pipe/measureCrosstalk.py
Add options for validation/rejection.  Ensure amplifier ordering is correct.
=> DM-30170: Define crosstalk tests for cp_verify

python/lsst/cp/pipe/defects.py
This PR removes references to `getFilterLabel` and similarly-named methods, replacing them with `getFilter` (etc.) methods backed by `FilterLabel`.
=> DM-27177: Deprecate transitional getFilterLabel API

python/lsst/cp/pipe/cpCombine.py, python/lsst/cp/pipe/cpSkyTask.py
Add method to set the filter label, which should reduce log noise.
=> DM-31986: "filter label mismatch" on loading cp_pipe calibration

python/lsst/cp/pipe/cpCombine.py
Convert per-amp scales to an image.
This image can then be subset to match the subregion used in the data,
avoiding potential geometry mismatch.
=> DM-35135: cpCombine partial reads interferes with amplifier-level scaling

pipelines/LsstCam/cpDeferredCharge.yaml, pipelines/cpDeferredCharge.yaml, python/lsst/cp/pipe/__init__.py, python/lsst/cp/pipe/deferredCharge.py, tests/test_deferredCharge.py
This change adds a task to construct a CTI dataset from the set of measurements created by `ip_isr`.
=> DM-33138: Add CTI correction to ip_isr

python/lsst/cp/pipe/cpSkyTask.py, ups/cp_pipe.table
=> DM-29835: Use background fitting code from pipe_tasks (v24 backport)

python/lsst/cp/pipe/makeBrighterFatterKernel.py
Remove masking that appears unnecessary.
=> DM-36262: length of mask and covariance can disagree in BrighterFatterKernelSolveTask

python/lsst/cp/pipe/defects.py, tests/test_defects.py
Handle exception caused by a single constant pixel value.
=> DM-36358: "broken" amplifiers trigger a failure in setting the threshold for defects

python/lsst/cp/pipe/cpCombine.py, python/lsst/cp/pipe/cpSkyTask.py
This PR replaces all requests for the `Exposure.filterLabel` Middleware component with `Exposure.filter`.
=> DM-36507: Remove references to filterLabel component from cp_pipe

python/lsst/cp/pipe/deferredCharge.py
Fix CTI output connection, making it a calibration.
=> DM-36280: Fix incorrect dataset type for CTI dataset in IsrTask

pipelines/Latiss/cpSky.yaml, pipelines/cpSky.yaml, python/lsst/cp/pipe/cpSkyTask.py
Switch cpSky to operate on postISRCCD datasetType.
=> DM-36885: Ensure cp_pipe only uses a different ISR output when needed

python/lsst/cp/pipe/ptc/cpExtractPtcTask.py
Use NaN instead of None to prevent potential serialization issues.
=> DM-37643: ci_cpp_gen3 fails on cpPtcExtract when noise is None

python/lsst/cp/pipe/defects.py, python/lsst/cp/pipe/linearity.py, python/lsst/cp/pipe/makeBrighterFatterKernel.py, python/lsst/cp/pipe/pdCorrection.py, python/lsst/cp/pipe/ptc/cpExtractPtcTask.py, python/lsst/cp/pipe/ptc/cpSolvePtcTask.py
Add updateMetadataFromExposures calls.
=> DM-36390: calibrations should track sequencer crc

python/lsst/cp/pipe/ptc/cpExtractPtcTask.py, python/lsst/cp/pipe/ptc/cpSolvePtcTask.py, tests/test_ptc.py
PTC improvements:
- Ensure all outputRefs have a matching outputCovariance (this is a problem blocking DM-37383).
- Try to get read noise from the exposure header.
- Get ampNames for the solve task from a non-dummy input, and anticipate associated bug fix on the PTC dataset in `ip_isr`.
- Update tests to pass full set of taskMetadata to mimic real butler behavior.
=> DM-38163: Update PTC to avoid potential failures

python/lsst/cp/pipe/ptc/cpExtractPtcTask.py, python/lsst/cp/pipe/ptc/cpSolvePtcTask.py, tests/test_ptc.py
This PR also moves a couple of tests to ip_isr where they are closer to the code they are testing, in addition to fixing an index error.
=> DM-38309: Update to use new PhotonTransferCurveDataset internal format.

tests/test_deferredCharge.py
Update deferred charge test value.
=> DM-38562:  cp_pipe test fails with lmfit 1.1.0

python/lsst/cp/pipe/cpCombine.py
Populate a visitInfo for combined calibration.
=> DM-38486: Combined dark seems to not have exposure time

python/lsst/cp/pipe/linearity.py
This will be used for TS8 and LSSTCam data taken at SLAC for Run 6 testing.
=> DM-39140: add photodiode integration algorithm for use with CCOB

python/lsst/cp/pipe/linearity.py
Photodiode integrals should never return an array.
=> DM-39338:  flatten arrays in photodiode calibration

pipelines/Latiss/cpLinearitySolve.yaml, pipelines/LsstCam/cpLinearitySolve.yaml, pipelines/LsstCam/cpPtc.yaml, pipelines/LsstCam/cpPtcNoPhotodiode.yaml, pipelines/LsstTS8/cpLinearitySolve.yaml, pipelines/LsstTS8/cpPtc.yaml, pipelines/_ingredients/cpLinearitySolve.yaml, python/lsst/cp/pipe/linearity.py, python/lsst/cp/pipe/ptc/cpExtractPtcTask.py, python/lsst/cp/pipe/ptc/cpSolvePtcTask.py, python/lsst/cp/pipe/utils.py, tests/test_linearity.py, tests/test_ptc.py
This moves the photodiode connections and integration code from the linearity code to the PTC code.  This will use the photoCharges part of the PTC dataset which was previously unfilled.
This also updates the default PTC and linearity pipelines for LSSTCam as appropriate.
=> DM-38944: Move photodiode computations from linearity to ptc code.

python/lsst/cp/pipe/cpDarkTask.py, python/lsst/cp/pipe/utils.py
This PR removes the old ad-hoc exposure time scaling, and replaces it with a scaling of the variance plane solely for the CR detection.  This resolves the signal-to-noise issue that was allowing a large fraction of pixels to pass the "condition 3" test.
=> DM-33862: Very high flux flats trigger tons of CR detections

pipelines/DarkEnergyCamera/cpFlat.yaml, pipelines/Latiss/cpBias.yaml, pipelines/Latiss/cpDark.yaml, pipelines/Latiss/cpFlat.yaml, pipelines/Latiss/cpFringe.yaml, pipelines/Latiss/cpPtc.yaml, pipelines/Latiss/cpSky.yaml, pipelines/Latiss/findDefects.yaml, pipelines/Latiss/findDefectsPostFlat.yaml, pipelines/Latiss/measurePtcWithLinearity.yaml, pipelines/LsstCam/cpDeferredCharge.yaml, pipelines/LsstCamImSim/cpBias.yaml, pipelines/LsstCamImSim/cpDark.yaml, pipelines/LsstCamImSim/cpFlat.yaml, pipelines/LsstCamImSim/cpPtc.yaml, pipelines/LsstComCam/cpBias.yaml, pipelines/LsstComCam/cpDark.yaml, pipelines/LsstComCam/cpFlat.yaml, pipelines/LsstComCam/cpPtc.yaml, pipelines/_ingredients/cpBias.yaml, pipelines/_ingredients/cpDark.yaml, pipelines/_ingredients/cpDeferredCharge.yaml, pipelines/_ingredients/cpFlat.yaml, pipelines/_ingredients/cpFlatSingleChip.yaml, pipelines/_ingredients/cpFringe.yaml, pipelines/_ingredients/cpPtc.yaml, pipelines/_ingredients/cpSky.yaml, pipelines/_ingredients/findDefects.yaml, pipelines/_ingredients/measureCrosstalk.yaml, python/lsst/cp/pipe/defects.py
Use explicit names for the ISR task calls.
=> DM-37383: Add package to support DM processing of camera runs

python/lsst/cp/pipe/ptc/cpSolvePtcTask.py, tests/test_linearity.py
This fixes a bug where low gains (<0.5) were not allowed in the fit.  It also now changes `maxADUInitialPtcOutlierFit` to default of units of electrons that can then be scaled by an initial estimate of the gain.  This allows the cutoff to be approximately invariant across a range of gain settings.
=> DM-42024: Allow for low gains and allow initial outlier cutoff to have units of electrons.

python/lsst/cp/pipe/cpCombine.py
Prevent nan values.
Jenkins returns nan values that do not appear when manually running.
=> DM-42643:  Pre-process data into catalog format for analysis_tools

pipelines/DarkEnergyCamera/RunIsrForCrosstalkSources.yaml
Changed `DarkEnergyCamera` to `DECam` in response to RFC-775.
=> DM-33453: Update pipeline references in response to RFC-775.

python/lsst/cp/pipe/defects.py, tests/test_defects.py
Add counters for defect pixels.
=> DM-42161: eo_pipe/cp_verify parity: defects

pipelines/Latiss/findDefectsCombined.yaml, pipelines/_ingredients/cpBias.yaml, pipelines/_ingredients/cpDarkForDefects.yaml, python/lsst/cp/pipe/defects.py, tests/test_defects.py
This also changes the general defect pipeline to mark saturated pixels but not count them as bad/interpolate/anything so that the defect finding code can know which pixels were saturated.
=> DM-43377: Add more features to defect finding code and update LATISS pipeline.

doc/lsst.cp.pipe/index.rst, doc/lsst.cp.pipe/tasks/lsst.cp.pipe.CpDarkTask.rst, doc/lsst.cp.pipe/tasks/lsst.cp.pipe.CpFlatMeasureTask.rst, doc/lsst.cp.pipe/tasks/lsst.cp.pipe.CpFlatNormalizationTask.rst, doc/lsst.cp.pipe/tasks/lsst.cp.pipe.CpFringeTask.rst, doc/lsst.cp.pipe/tasks/lsst.cp.pipe.CpSkyCombineTask.rst, doc/lsst.cp.pipe/tasks/lsst.cp.pipe.CpSkyImageTask.rst, doc/lsst.cp.pipe/tasks/lsst.cp.pipe.CpSkyScaleMeasureTask.rst, doc/lsst.cp.pipe/tasks/lsst.cp.pipe.CpSkySubtractBackgroundTask.rst
The tasks are all available in the `lsst.cp.pipe` namespace and the docs need to reference them there.
=> DM-44259-hotfix-docs: Remove extraneous paths from task names in docs.

python/lsst/cp/pipe/cpFilterScan.py
The previous version of this code searched for points that we below the thresholds in the positive wavelength direction, assigning the endpoint if it hadn't already been set.  This worked fine.  The search in the negative wavelength direction, however, searched for the first pixel above the threshold, and assigned the endpoint if it wasn't already set.  This would find the first pixel lower than the peak, set that as the endpoint, and due to the `if not None` checks, never set any lower pixel as the endpoint.  This resulted in the fitting code only getting slightly more than the upper-half of the profile.
The updated code searches both directions for pixels above or equal to the thresholds, allowing newer endpoints to overwrite those that exist.  This fixes the search in the negative …
=> DM-45201: Fix fiber spectrograph fitting in CpMonochromatorScanTask

python/lsst/cp/pipe/ptc/cpPtcExtract.py, python/lsst/cp/pipe/utils.py
Move `getReadNoise` to lsst.cp.pipe.utils, and make it able to find read noise entries in either the exposure or task metadata.
=> DM-45300: Begin deprecation of task metadata in cp_pipe/cp_verify

python/lsst/cp/pipe/cpCombine.py, python/lsst/cp/pipe/cpLinearitySolve.py, python/lsst/cp/pipe/ptc/cpPtcExtract.py, python/lsst/cp/pipe/ptc/cpPtcSolve.py, python/lsst/cp/pipe/utils.py, tests/test_ptc.py
This PR implements a bunch of small updates found in the development of DM-45856, including the `doAmpOffsetGainRatioFixup` that uses flat-pair amp offsets to fix up noisy gain ratios determined from the individual amplifier PTC fitting.
=> DM-46308: Updates to PTC fitting, including doAmpOffsetGainRatioFixup for new IsrTaskLSST

pipelines/_ingredients/cpBfk.yaml, pipelines/_ingredients/cpBfkLSST.yaml, pipelines/_ingredients/cpBiasBootstrapLSST.yaml, pipelines/_ingredients/cpBiasLSST.yaml, pipelines/_ingredients/cpDarkBootstrapLSST.yaml, pipelines/_ingredients/cpDarkLSST.yaml, pipelines/_ingredients/cpDefectsLSST.yaml, pipelines/_ingredients/cpFilterScanLSST.yaml, pipelines/_ingredients/cpFlatBootstrapLSST.yaml, pipelines/_ingredients/cpFlatBootstrapSingleChipLSST.yaml, pipelines/_ingredients/cpFlatLSST.yaml, pipelines/_ingredients/cpFlatSingleChipLSST.yaml, pipelines/_ingredients/cpLinearizerLSST.yaml, pipelines/_ingredients/cpPtcLSST.yaml, pipelines/_ingredients/cpSkyLSST.yaml, python/lsst/cp/pipe/__init__.py, python/lsst/cp/pipe/_configure.py, python/lsst/cp/pipe/cpBfk.py, tests/test_pipelines.py
This PR is the first implementation ticket for RFC-1044.  The pipelines in this PR are not directly tested; the testing, in conjunction with the LATISS pipelines, is being done on DM-46356.
=> DM-45856: Add new calibration pipelines for IsrTaskLSST to _ingredients

python/lsst/cp/pipe/cpLinearitySolve.py
This makes sure that when using the photodiode (much larger scaling) that things converge correctly when checking residuals.
=> DM-46546: Linearity fit residual test should use linear fit parameters as initial guess

python/lsst/cp/pipe/ptc/cpPtcExtract.py
Only exclude mask planes we've asked to exclude.
=> DM-47636: Switch CROSSTALK masking to use subtrahend masking

pipelines/_ingredients/cpIlluminationCorrectionLSST.yaml
This updates the density cut which had been erroneously applied; changes to 4th order chebyshev polynomials (per detector); and updates to v2 connection dataset type names.
=> DM-49369: Update LSST illumination correction configurations
